# Generated by Django 3.2.7 on 2021-10-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('phone', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('date_oder', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('id_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('decription', models.TextField()),
                ('detail', models.TextField()),
                ('price', models.FloatField()),
                ('sale', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category_product')),
                ('product_detail_id', models.ManyToManyField(to='news.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.product')),
            ],
        ),
    ]
