# Generated by Django 3.2.7 on 2021-10-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_product',
            name='category_owner',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
