# Generated by Django 3.2.7 on 2021-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_product_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_product',
            name='category_owner',
            field=models.CharField(choices=[{'Woman', 'Men'}], default='Men', max_length=400, null=True),
        ),
    ]
