# Generated by Django 3.2.7 on 2021-10-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_product_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
